name: Add Review Label
on:
  pull_request_review:
    types:
      - submitted

jobs:
  check_reviews:
    runs-on: ubuntu-latest
    # labelがない時だけ実行する。
    if: ${{ contains( github.event.pull_request.labels.*.name, 'Reviewed') == 'false' }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Count Approve
        uses: luisrjaeger/approved-event-checker@1.0.0 # https://github.com/marketplace/actions/approved-event-checker
        id: approved
        with:
          approvals: 2
          check_changes_requested: true # change_requestがある場合はさ、approveにしない。
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Approved
        run: echo "Approval is ${{ steps.approved.outputs.approved }}"
      - name: Add Reviewed Label
        if: ${{ steps.approved.outputs.approved == 'true' }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['Reviewed']
            })